package io.nanovc.nano_jgit_analyzer;

import io.nanovc.ClockBase;
import io.nanovc.areas.ByteArrayHashMapArea;
import io.nanovc.junit.TestDirectory;
import io.nanovc.junit.TestDirectoryExtension;
import io.nanovc.memory.MemoryCommit;
import io.nanovc.memory.MemoryNanoRepo;
import io.nanovc.memory.MemorySearchResults;
import io.nanovc.searches.commits.SimpleSearchQueryDefinition;
import io.nanovc.searches.commits.expressions.AllRepoCommitsExpression;
import io.nanovc.searches.commits.expressions.TipOfExpression;
import io.nanovc.timestamps.InstantTimestamp;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.io.IOException;
import java.nio.file.Path;
import java.time.Instant;

@ExtendWith(TestDirectoryExtension.class)
public class AnalysisTests
{
    /**
     * Tests git analysis.
     *
     * @param testPath The path to a temporary folder for this test.
     */
    @Test
    public void testAnalysis(@TestDirectory(useTestName = true) Path testPath) throws GitAPIException, IOException
    {
        // Create the nano repo where we will load the entire Git repo:
        MemoryNanoRepo nanoRepo = NanoJGitAnalyzer.createNanoRepoFromGitUrl("https://github.com/nanovc/nano-jgit-analyzer.git", testPath);

        // Search the repo:
        System.out.println("MEMORY REPO: Tip");
        MemorySearchResults search = nanoRepo.search(new SimpleSearchQueryDefinition(new TipOfExpression(new AllRepoCommitsExpression()), null, null));
        for (MemoryCommit commit : search.getCommits())
        {
            ByteArrayHashMapArea checkout = nanoRepo.checkout(commit);
            System.out.println(checkout.asListString());
        }
    }

    static class Commit
    {
        public String id;

        public long timestamp;

        /**
         * A repository slug is a URL-friendly version of a repository name,
         * automatically generated by Bitbucket for use in the URL.
         * For example, if your repository name was 'føøbar', in the URL it would become 'foobar'.
         * Similarly, 'foo bar' would become 'foo-bar'.
         * https://confluence.atlassian.com/bitbucket/what-is-a-slug-224395839.html
         */
        public String slug;

        public String author_email;

        public String author_name;

        public String message;
    }
}
